HW 7 is done
Pos1t1veM1ndset/shiny-homework pull request #8
Opened 2022-12-03 10:39 UTC by Pos1t1veM1ndset

## Домашнее задание №7 «Утилита для копирования файлов»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-02-11 16:57 UTC, antonpriyma commented on hw07_file_copying/copy.go
> +		return fmt.Errorf("cannot open input file, erorr: %w", err)
опечатка)

2023-02-11 17:04 UTC, antonpriyma commented on hw07_file_copying/copy.go
> +	defer func() {
Этот defer стоит вынести после проверки ошибки. Правило -- нельзя использовать значение до проверки ошибки.

2023-02-11 17:06 UTC, antonpriyma commented on hw07_file_copying/copy.go
> +			log.Println(err)
Есть ли смысл в такой проверке? Кажется, можно оставить defer fi.Close

2023-02-11 17:08 UTC, antonpriyma commented on hw07_file_copying/copy.go
> +	fo, err := os.OpenFile(toPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o755)
не стоит ли тут просто os.Create(toPath)?

2023-02-11 17:08 UTC, antonpriyma commented on hw07_file_copying/copy.go
> +	defer func() {
то же самое с проверкой ошибки до дефера

2023-02-11 17:09 UTC, antonpriyma commented on hw07_file_copying/copy.go
> +	fi.Seek(offset, 0)
вместо 0 будет лучше написать io.SeekStart. + Здесь стоит добавить проверку ошибки

2023-02-11 17:11 UTC, antonpriyma commented on hw07_file_copying/copy.go
> +	_, err = io.CopyN(fo, barReader, limit)
тут так же стоит проверять, сколько записалось:

```
written, err := io.CopyN(dstFile, srcFile, limit)
	if written < limit {
		return some error
	}
```

2023-02-11 17:13 UTC, antonpriyma commented on hw07_file_copying/copy.go
> +			log.Println(err)
тут на ваше усмотрение. Но на практике чаще пишут просто defer fi.Close

2023-02-11 17:14 UTC, antonpriyma requested changes
В целом код рабочий, тесты хорошо все покрывают. Но есть пару недочетов, доработайте, пожалуйста

2023-02-13 04:44 UTC, Pos1t1veM1ndset commented on hw07_file_copying/copy.go
> +	fo, err := os.OpenFile(toPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o755)
Проверил, что при создании существующего файла не возвращается ошибка, так и сделаю, спасибо!

2023-02-13 17:06 UTC, antonpriyma approved these changes

2023-02-13 17:45 UTC, merged